<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="EPPlus" Version="8.5.0" />
    <PackageReference Include="Hangfire" Version="1.8.23" />
    <PackageReference Include="iTextSharp.LGPLv2.Core" Version="3.7.12" />
    <PackageReference Include="MailKit" Version="4.15.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.14" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="9.0.14" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="9.0.14" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
    <PackageReference Include="Xero.NetStandard.OAuth2" Version="13.0.0" />
    <PackageReference Include="Xero.NetStandard.OAuth2Client" Version="1.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flowdesks.Application\Flowdesks.Application.csproj" />
    <ProjectReference Include="..\Flowdesks.Persistence\Flowdesks.Persistence.csproj" />
  </ItemGroup>

</Project>
