using Flowdesks.Domain.Common;
using Flowdesks.Domain.Entities.Identity;

namespace Flowdesks.Domain.Entities.Note
{
    public class Note : AuditableEntity<Guid>
    {
        public string Text { get; set; }     
        public string EntityType { get; set; } //EntityType Enum
        public Guid EntityId { get; set; }
        public bool AutoGenerated { get; set; }

        public Guid? UserId { get; set; }
        public virtual ApplicationUser? User { get; set; }
    }
}