using Flowdesks.Shared.Enums;

namespace Flowdesks.Application.Responses.Notes;

public class NoteResponse
{
    public Guid Id { get; set; }
    public Guid? UserId { get; set; }
    public string AuthorFullName { get; set; }
    public string Text { get; set; }
    public EntityType EntityType { get; set; }
    public bool AutoGenerated { get; set; }
    public Guid EntityId { get; set; }
    public string CreatedBy { get; set; }
    public DateTime CreatedOn { get; set; }
    public string LastModifiedBy { get; set; }
    public DateTime? LastModifiedOn { get; set; }
}