<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="9.0.14" />
    <PackageReference Include="Xero.NetStandard.OAuth2" Version="13.0.0" />
    <PackageReference Include="Xero.NetStandard.OAuth2Client" Version="1.6.0" />
  </ItemGroup>

</Project>
